services:
  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp-automa-back-end
    restart: always
    env_file: 
      - .env
    ports:
      - "8007:8007"

  #db:
  #  image: postgres:14.10
  #  container_name: db_producao
  #  environment:
  #    POSTGRES_USER: admin
  #    POSTGRES_PASSWORD: postgre
  #    POSTGRES_DB: desenvolvimento
  #  ports:
  #    - "5432:5432"
  #  volumes:
  #    - postgres_data:/var/lib/postgresql/data

  # db_tests:
  #   image: postgres:14.10
  #   container_name: db_producao_tests
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: postgre
  #     POSTGRES_DB: tests
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres_data_tests:/var/lib/postgresql/data

# volumes:
#   postgres_data:
#   postgres_data_tests:
