services:
  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp-automa-back-end
    env_file: 
      - .env
    ports:
      - "8007:8007"
    depends_on:
      - db

  db:
    image: postgres:14.10
    container_name: automa_local
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: desenvolvimento
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
